// components/ProductCard.vue
<template>
  <article
    class="group relative bg-white rounded-sm overflow-hidden transition-all duration-500 cursor-pointer"
    @click="$emit('click', product)"
  >
    <!-- Badge -->
    <div
      v-if="isNew"
      class="absolute top-4 left-4 z-10 bg-white text-charcoal border border-gray-100 text-[10px] uppercase tracking-[0.2em] font-medium px-3 py-1 shadow-sm"
    >
      Nouveau
    </div>
    <div
      v-else-if="product.featured"
      class="absolute top-4 left-4 z-10 bg-gold text-white text-[10px] uppercase tracking-[0.2em] font-medium px-3 py-1 shadow-sm"
    >
      En vedette
    </div>

    <!-- Image Container -->
    <div class="relative aspect-[4/5] overflow-hidden bg-gray-50">
      <!-- Image Principale -->
      <img
        :src="primaryImage"
        :alt="product.title"
        class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
        loading="lazy"
      />
      
      <!-- Image Secondaire (au hover) -->
      <img
        v-if="secondaryImage"
        :src="secondaryImage"
        :alt="product.title"
        class="absolute inset-0 w-full h-full object-cover opacity-0 group-hover:opacity-100 transition-opacity duration-700"
        loading="lazy"
      />

      <!-- Bouton Voir produit discret -->
      <div 
        class="absolute inset-x-0 bottom-0 p-4 opacity-0 group-hover:opacity-100 transition-opacity duration-500 flex justify-center"
      >
        <span class="bg-white/90 backdrop-blur-sm text-charcoal text-[10px] uppercase tracking-[0.2em] font-medium px-6 py-3 shadow-sm hover:bg-charcoal hover:text-white transition-colors duration-300">
          Découvrir
        </span>
      </div>
    </div>

    <!-- Infos Produit -->
    <div class="pt-5 pb-2 text-center space-y-2">
      <!-- Catégorie -->
      <p v-if="product.category" class="text-[10px] font-medium text-gray-400 uppercase tracking-[0.2em]">
        {{ product.category }}
      </p>

      <!-- Titre -->
      <h3 class="font-serif text-lg text-charcoal line-clamp-1 group-hover:text-gold transition-colors duration-300">
        {{ product.title }}
      </h3>

      <!-- Prix -->
      <div class="pt-1">
        <span class="text-sm font-light text-gray-500">
          {{ formattedPrice }}
        </span>
      </div>
    </div>
  </article>
</template>

<script setup lang="ts">
import type { Product } from '~/types'

const props = defineProps<{
  product: Product
  showAddToCart?: boolean
}>()

defineEmits<{
  click: [product: Product]
  'add-to-cart': [product: Product]
}>()

// Computed
const isNew = computed(() => {
  if (!props.product.created_at) return false
  const created = Date.parse(props.product.created_at)
  const fortyEightHours = 48 * 60 * 60 * 1000 // 48 heures
  return (Date.now() - created) <= fortyEightHours
})

const primaryImage = computed(() => {
  return props.product.image || props.product.images?.[0] || '/images/placeholder.svg'
})

const secondaryImage = computed(() => {
  if (props.product.images && props.product.images.length > 0) {
    if (props.product.image) {
      return props.product.images[0]
    }
    return props.product.images[1] || null
  }
  return null
})

const formattedPrice = computed(() => {
  return new Intl.NumberFormat('fr-FR').format(props.product.price) + ' FCFA'
})
</script>

// src/components/ProductCard.tsx
import Link from "next/link";
import Image from "next/image";

interface Product {
  id: string;
  title: string;
  price: number;
  image: string;
  category: string;
  isNew?: boolean;
}

interface ProductCardProps {
  product: Product;
}

export default function ProductCard({ product }: ProductCardProps) {
  const formatPrice = (price: number) => {
    return new Intl.NumberFormat("fr-FR").format(price) + " FCFA";
  };

  return (
    <div className="group relative flex flex-col bg-white">
      {/* Image container */}
      <Link href={`/produits/${product.id}`} className="relative aspect-[4/5] overflow-hidden bg-gray-50 border border-transparent group-hover:border-gray-100 transition-colors">
        <Image
          src={product.image || "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80"}
          alt={product.title}
          fill
          className="object-cover object-center group-hover:scale-105 transition-transform duration-700 ease-out"
          sizes="(min-width: 1024px) 25vw, (min-width: 768px) 33vw, 50vw"
        />
        {product.isNew && (
          <span className="absolute top-4 left-4 bg-white text-charcoal text-[9px] uppercase tracking-[0.2em] px-3 py-1.5 z-10 border border-gray-100 shadow-sm">
            Nouveau
          </span>
        )}
        
        {/* Quick Add Overlay */}
        <div className="absolute inset-x-0 bottom-0 p-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300 translate-y-4 group-hover:translate-y-0 flex justify-center">
          <button className="w-full bg-charcoal/90 backdrop-blur-sm text-white text-[10px] uppercase tracking-[0.2em] py-3.5 hover:bg-gold transition-colors shadow-lg">
            Ajout Rapide
          </button>
        </div>
      </Link>

      {/* Info */}
      <div className="pt-5 pb-2 text-center flex flex-col items-center">
        <p className="text-[9px] uppercase tracking-[0.2em] text-gray-400 mb-1.5">
          {product.category}
        </p>
        <Link href={`/produits/${product.id}`}>
          <h3 className="text-charcoal font-serif text-lg mb-1 group-hover:text-gold transition-colors">
            {product.title}
          </h3>
        </Link>
        <p className="text-gray-500 font-light text-sm mt-1">
          {formatPrice(product.price)}
        </p>
      </div>
    </div>
  );
}
