// src/app/commander/page.tsx
"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import { useCart } from "@/context/CartContext";
import { supabase } from "@/lib/supabase";

const SHIPPING_FEES: Record<string, number> = {
  "N'Djamena": 1000,
  "Moundou": 2000,
  "Sarh": 2000,
  "Abeche": 2500,
  "Bongor": 1500,
  "Kelo": 2000,
  "Pala": 2000,
  "Koumra": 2000,
  "Faya-Largeau": 3000,
};

const FREE_SHIPPING_THRESHOLD = 20000;

export default function CheckoutPage() {
  const { cartItems, subtotal, clearCart } = useCart();
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [city, setCity] = useState("N'Djamena");
  const [address, setAddress] = useState("");
  const [shippingFee, setShippingFee] = useState(1000);
  const [loading, setLoading] = useState(false);
  const [orderPlaced, setOrderPlaced] = useState(false);

  useEffect(() => {
    if (subtotal >= FREE_SHIPPING_THRESHOLD) {
      setShippingFee(0);
    } else {
      setShippingFee(SHIPPING_FEES[city] || 1500);
    }
  }, [city, subtotal]);

  const formatPrice = (price: number) => {
    return new Intl.NumberFormat("fr-FR").format(price) + " FCFA";
  };

  const generateOrderNumber = () => {
    const date = new Date();
    const year = date.getFullYear().toString().slice(-2);
    const month = (date.getMonth() + 1).toString().padStart(2, "0");
    const day = date.getDate().toString().padStart(2, "0");
    const random = Math.random().toString(36).substring(2, 6).toUpperCase();
    return `SC${year}${month}${day}-${random}`;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (cartItems.length === 0) return;

    setLoading(true);
    const orderNumber = generateOrderNumber();
    const total = subtotal + shippingFee;

    const orderItems = cartItems.map(item => ({
      product_id: item.product.id,
      product_title: item.product.title,
      product_price: item.product.price,
      quantity: item.quantity,
      subtotal: item.product.price * item.quantity,
    }));

    try {
      // 1. Insert order to Supabase
      const { data, error } = await supabase
        .from("orders")
        .insert({
          order_number: orderNumber,
          client_name: name,
          client_phone: phone,
          client_city: city,
          client_address: address,
          items: orderItems,
          subtotal,
          shipping_fee: shippingFee,
          total,
          payment_method: "cash",
          status: "pending",
        })
        .select()
        .single();

      if (error) throw error;

      // 2. Format WhatsApp Message
      const lines = [
        "=============================",
        "   NOUVELLE COMMANDE",
        "=============================",
        "",
        `Numéro: ${orderNumber}`,
        "",
        "--- INFORMATIONS CLIENT ---",
        `Nom: ${name}`,
        `Tel: ${phone}`,
        `Ville: ${city}`,
        `Adresse: ${address}`,
        "",
        "--- PRODUITS COMMANDÉS ---",
        ...orderItems.map(item => `- ${item.product_title} x${item.quantity} = ${formatPrice(item.subtotal)}`),
        "",
        "--- RÉCAPITULATIF ---",
        `Sous-total: ${formatPrice(subtotal)}`,
        `Livraison: ${shippingFee === 0 ? "GRATUITE" : formatPrice(shippingFee)}`,
        `TOTAL: ${formatPrice(total)}`,
        "",
        "Mode de paiement: Paiement à la livraison",
        "",
        "=============================",
      ];

      const message = encodeURIComponent(lines.join("\n"));
      
      // 3. Clear cart and set success state
      clearCart();
      setOrderPlaced(true);

      // 4. Redirect to WhatsApp
      window.location.href = `https://wa.me/23563462615?text=${message}`;

    } catch (err) {
      console.error("Erreur de création de commande:", err);
      alert("Une erreur s'est produite lors de la validation. Veuillez réessayer.");
    } finally {
      setLoading(false);
    }
  };

  if (orderPlaced) {
    return (
      <div className="min-h-screen bg-cream pt-32 pb-24 flex items-center justify-center">
        <div className="text-center space-y-6 max-w-md px-6">
          <h2 className="text-3xl font-serif text-charcoal">Merci pour votre commande !</h2>
          <p className="text-charcoal/50 text-sm font-light leading-relaxed">
            Votre commande a été enregistrée avec succès. Vous allez être redirigé vers WhatsApp pour finaliser la livraison avec notre conseillère.
          </p>
          <p className="text-xs text-gold font-semibold uppercase tracking-widest">Paiement à la livraison</p>
          <Link
            href="/produits"
            className="inline-block bg-charcoal text-white px-8 py-4.5 text-[9px] uppercase tracking-[0.25em] font-semibold hover:bg-gold hover:text-charcoal transition-all duration-500 rounded-sm shadow-md"
          >
            Retour à la boutique
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-cream pt-32 pb-24">
      <div className="max-w-7xl mx-auto px-6 sm:px-8 lg:px-12">
        <div className="space-y-4 mb-16 text-center lg:text-left">
          <span className="text-[10px] font-semibold tracking-[0.25em] uppercase text-gold">Finaliser</span>
          <h1 className="text-4xl lg:text-5xl font-serif font-light text-charcoal">Votre Commande</h1>
        </div>
        
        {cartItems.length === 0 ? (
          <div className="text-center py-24 border border-sand/40 rounded-sm bg-white shadow-sm max-w-2xl mx-auto px-6">
            <h2 className="text-2xl font-serif text-charcoal mb-4">Votre panier est vide</h2>
            <p className="text-charcoal/50 text-sm font-light mb-8 max-w-sm mx-auto leading-relaxed">
              Ajoutez des produits à votre panier avant de passer à la caisse.
            </p>
            <Link
              href="/produits"
              className="inline-block bg-charcoal text-white px-8 py-4.5 text-[9px] uppercase tracking-[0.25em] font-semibold hover:bg-gold hover:text-charcoal transition-all duration-500 rounded-sm shadow-md"
            >
              Voir nos produits
            </Link>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="grid lg:grid-cols-12 gap-12 items-start">
            
            {/* Formulaire */}
            <div className="lg:col-span-7 xl:col-span-8 space-y-8 animate-fade-in-up">
              <div className="bg-white p-8 md:p-12 border border-sand/40 rounded-sm shadow-[0_4px_25px_rgba(26,26,26,0.02)]">
                <h2 className="text-[9px] uppercase tracking-[0.25em] font-semibold text-gold mb-8 pb-4 border-b border-sand/30">
                  1. Vos coordonnées
                </h2>
                
                <div className="grid md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-[9px] uppercase tracking-widest text-charcoal font-semibold mb-2">Nom complet *</label>
                    <input 
                      type="text" 
                      required
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                      className="w-full border border-sand px-4 py-3.5 bg-cream/30 focus:bg-white focus:border-gold outline-none transition-all font-light text-sm rounded-sm text-charcoal" 
                      placeholder="Ex: Adoum Mahamat" 
                    />
                  </div>
                  <div>
                    <label className="block text-[9px] uppercase tracking-widest text-charcoal font-semibold mb-2">Numéro WhatsApp *</label>
                    <input 
                      type="tel" 
                      required
                      value={phone}
                      onChange={(e) => setPhone(e.target.value)}
                      className="w-full border border-sand px-4 py-3.5 bg-cream/30 focus:bg-white focus:border-gold outline-none transition-all font-light text-sm rounded-sm text-charcoal" 
                      placeholder="Ex: 66 00 00 00" 
                    />
                  </div>
                  <div>
                    <label className="block text-[9px] uppercase tracking-widest text-charcoal font-semibold mb-2">Ville *</label>
                    <select
                      value={city}
                      onChange={(e) => setCity(e.target.value)}
                      className="w-full border border-sand px-4 py-3.5 bg-cream/30 focus:bg-white focus:border-gold outline-none transition-all font-light text-sm rounded-sm text-charcoal cursor-pointer"
                    >
                      {Object.keys(SHIPPING_FEES).map(c => (
                        <option key={c} value={c}>{c}</option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-[9px] uppercase tracking-widest text-charcoal font-semibold mb-2">Adresse de livraison / Quartier *</label>
                    <input 
                      type="text" 
                      required
                      value={address}
                      onChange={(e) => setAddress(e.target.value)}
                      className="w-full border border-sand px-4 py-3.5 bg-cream/30 focus:bg-white focus:border-gold outline-none transition-all font-light text-sm rounded-sm text-charcoal" 
                      placeholder="Ex: Quartier Sabangali, rue 20..." 
                    />
                  </div>
                </div>
              </div>

              <div className="bg-white p-8 md:p-12 border border-sand/40 rounded-sm shadow-[0_4px_25px_rgba(26,26,26,0.02)]">
                <h2 className="text-[9px] uppercase tracking-[0.25em] font-semibold text-gold mb-8 pb-4 border-b border-sand/30">
                  2. Paiement
                </h2>
                <div className="border border-gold p-6 text-center bg-sand/10 rounded-sm">
                  <p className="text-charcoal font-semibold text-xs uppercase tracking-widest mb-1.5">Paiement à la livraison</p>
                  <p className="text-charcoal/50 font-light text-xs">Vous paierez en espèces lors de la réception de votre commande.</p>
                </div>
              </div>
            </div>

            {/* Récapitulatif */}
            <div className="lg:col-span-5 xl:col-span-4 lg:sticky lg:top-28">
              <div className="bg-white p-6 md:p-8 border border-sand/40 rounded-sm shadow-[0_4px_25px_rgba(26,26,26,0.02)]">
                <h2 className="text-[9px] uppercase tracking-[0.25em] font-semibold text-gold mb-6 pb-4 border-b border-sand/30">
                  Récapitulatif
                </h2>
                
                <div className="space-y-6 mb-8 max-h-[30vh] overflow-y-auto pr-1">
                  {cartItems.map((item) => (
                    <div key={item.product.id} className="flex gap-4 items-center">
                      <div className="w-16 h-20 bg-cream relative border border-sand/30 rounded-xs overflow-hidden flex-shrink-0">
                        <Image
                          src={item.product.image || "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80"}
                          alt={item.product.title}
                          fill
                          className="object-cover"
                        />
                      </div>
                      <div className="flex-1 flex flex-col justify-center">
                        <h3 className="text-charcoal font-serif text-sm font-medium truncate max-w-[150px]">{item.product.title}</h3>
                        <p className="text-charcoal/40 text-[9px] uppercase tracking-widest mt-1">Qté: {item.quantity}</p>
                        <p className="text-charcoal/80 font-medium text-sm mt-1.5">{formatPrice(item.product.price * item.quantity)}</p>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="border-t border-sand/30 pt-6 space-y-4 mb-8">
                  <div className="flex justify-between text-xs text-charcoal/50 font-light">
                    <span>Sous-total</span>
                    <span className="font-medium text-charcoal/80">{formatPrice(subtotal)}</span>
                  </div>
                  <div className="flex justify-between text-xs text-charcoal/50 font-light">
                    <span>Livraison</span>
                    <span className="font-medium text-charcoal/80">
                      {shippingFee === 0 ? "GRATUITE" : formatPrice(shippingFee)}
                    </span>
                  </div>
                  <div className="flex justify-between items-end text-charcoal pt-4 border-t border-sand/30">
                    <span className="text-[9px] uppercase tracking-widest font-semibold pb-1">Total estimé</span>
                    <span className="text-2xl font-serif text-charcoal/90">{formatPrice(subtotal + shippingFee)}</span>
                  </div>
                </div>

                <button 
                  type="submit"
                  disabled={loading}
                  className="w-full bg-charcoal text-white py-5 text-[9px] uppercase tracking-[0.25em] font-semibold hover:bg-gold hover:text-charcoal transition-all duration-500 rounded-sm shadow-lg shadow-charcoal/5 disabled:opacity-50"
                >
                  {loading ? "Traitement..." : "Confirmer la commande"}
                </button>
                
                <div className="mt-6 flex items-center justify-center gap-2 text-[8px] uppercase tracking-widest text-charcoal/40 font-semibold">
                  <span>Paiement 100% sécurisé</span>
                </div>
              </div>
            </div>

          </form>
        )}
      </div>
    </div>
  );
}

// pages/commander.vue
<template>
  <div class="min-h-screen bg-ivory-100">
    <!-- Header -->
    <div class="bg-white border-b border-gray-100">
      <div class="max-w-container mx-auto px-4 py-6">
        <NuxtLink to="/produits" class="inline-flex items-center gap-2 text-gray-500 hover:text-charcoal transition-colors mb-4">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
          </svg>
          Continuer mes achats
        </NuxtLink>
        <h1 class="text-2xl lg:text-3xl font-bold text-charcoal">Finaliser ma commande</h1>
      </div>
    </div>

    <!-- Panier vide -->
    <div v-if="isEmpty" class="max-w-container mx-auto px-4 py-16 text-center">
      <div class="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-6">
        <svg class="w-12 h-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
        </svg>
      </div>
      <h2 class="text-xl font-bold text-charcoal mb-2">Votre panier est vide</h2>
      <p class="text-gray-500 mb-6">Ajoutez des produits pour passer commande</p>
      <NuxtLink to="/produits" class="inline-flex items-center gap-2 bg-charcoal text-white px-6 py-3 rounded-full font-medium">
        Voir les produits
      </NuxtLink>
    </div>

    <!-- Formulaire de commande -->
    <div v-else class="max-w-container mx-auto px-4 py-8">
      <div class="grid lg:grid-cols-3 gap-8">
        <!-- Formulaire (2/3) -->
        <div class="lg:col-span-2 space-y-6">
          <!-- Informations personnelles -->
          <div class="bg-white rounded-2xl p-6 shadow-soft">
            <h2 class="text-lg font-bold text-charcoal mb-4 flex items-center gap-2">
              <span class="w-8 h-8 bg-charcoal text-white rounded-full flex items-center justify-center text-sm">1</span>
              Vos informations
            </h2>
            
            <div class="grid md:grid-cols-2 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1.5">
                  Nom complet <span class="text-red-500">*</span>
                </label>
                <input
                  v-model="form.name"
                  type="text"
                  placeholder="Ex: Fatima Ibrahim"
                  class="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-gold/50 focus:border-gold outline-none transition-all"
                  :class="{ 'border-red-500': errors.name }"
                />
                <p v-if="errors.name" class="text-red-500 text-sm mt-1">{{ errors.name }}</p>
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1.5">
                  Téléphone <span class="text-red-500">*</span>
                </label>
                <input
                  v-model="form.phone"
                  type="tel"
                  placeholder="Ex: 66 00 00 00"
                  class="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-gold/50 focus:border-gold outline-none transition-all"
                  :class="{ 'border-red-500': errors.phone }"
                />
                <p v-if="errors.phone" class="text-red-500 text-sm mt-1">{{ errors.phone }}</p>
              </div>
            </div>
          </div>

          <!-- Adresse de livraison -->
          <div class="bg-white rounded-2xl p-6 shadow-soft">
            <h2 class="text-lg font-bold text-charcoal mb-4 flex items-center gap-2">
              <span class="w-8 h-8 bg-charcoal text-white rounded-full flex items-center justify-center text-sm">2</span>
              Adresse de livraison
            </h2>
            
            <div class="space-y-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1.5">
                  Ville <span class="text-red-500">*</span>
                </label>
                <select
                  v-model="form.city"
                  class="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-gold/50 focus:border-gold outline-none transition-all bg-white"
                  :class="{ 'border-red-500': errors.city }"
                >
                  <option value="">Sélectionnez une ville</option>
                  <option v-for="city in cities" :key="city" :value="city">{{ city }}</option>
                </select>
                <p v-if="errors.city" class="text-red-500 text-sm mt-1">{{ errors.city }}</p>
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1.5">
                  Quartier / Adresse complète <span class="text-red-500">*</span>
                </label>
                <input
                  v-model="form.address"
                  type="text"
                  placeholder="Ex: Moursal, près de la station Total"
                  class="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-gold/50 focus:border-gold outline-none transition-all"
                  :class="{ 'border-red-500': errors.address }"
                />
                <p v-if="errors.address" class="text-red-500 text-sm mt-1">{{ errors.address }}</p>
              </div>

              <!-- Info livraison -->
              <div class="bg-gold/10 border border-gold/20 rounded-xl p-4">
                <div class="flex gap-3">
                  <svg class="w-5 h-5 text-gold flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <div class="text-sm">
                    <p class="font-medium text-charcoal">Frais de livraison</p>
                    <p class="text-gray-600 mt-1">
                      Les frais de livraison seront confirmés par WhatsApp selon votre quartier 
                      <span class="text-charcoal">(généralement entre 500 et 2 000 FCFA à N'Djamena)</span>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Mode de paiement -->
          <div class="bg-white rounded-2xl p-6 shadow-soft">
            <h2 class="text-lg font-bold text-charcoal mb-4 flex items-center gap-2">
              <span class="w-8 h-8 bg-charcoal text-white rounded-full flex items-center justify-center text-sm">3</span>
              Mode de paiement
            </h2>
            
            <div class="grid sm:grid-cols-2 gap-3">
              <label
                v-for="method in paymentMethods"
                :key="method.value"
                class="relative flex items-center gap-3 p-4 border-2 rounded-xl cursor-pointer transition-all"
                :class="form.paymentMethod === method.value 
                  ? 'border-gold bg-gold/5' 
                  : 'border-gray-200 hover:border-gray-300'"
              >
                <input
                  v-model="form.paymentMethod"
                  type="radio"
                  :value="method.value"
                  class="sr-only"
                />
                <span class="text-2xl">{{ method.icon }}</span>
                <span class="font-medium text-charcoal">{{ method.label }}</span>
                <span
                  v-if="form.paymentMethod === method.value"
                  class="absolute top-2 right-2 w-5 h-5 bg-gold rounded-full flex items-center justify-center"
                >
                  <svg class="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7" />
                  </svg>
                </span>
              </label>
            </div>
            <p v-if="errors.paymentMethod" class="text-red-500 text-sm mt-2">{{ errors.paymentMethod }}</p>
          </div>

          <!-- Notes -->
          <div class="bg-white rounded-2xl p-6 shadow-soft">
            <h2 class="text-lg font-bold text-charcoal mb-4 flex items-center gap-2">
              <span class="w-8 h-8 bg-gray-200 text-gray-600 rounded-full flex items-center justify-center text-sm">4</span>
              Notes (optionnel)
            </h2>
            <textarea
              v-model="form.notes"
              rows="3"
              placeholder="Instructions spéciales pour la livraison, questions..."
              class="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-gold/50 focus:border-gold outline-none transition-all resize-none"
            />
          </div>
        </div>

        <!-- Récapitulatif (1/3) -->
        <div class="lg:col-span-1">
          <div class="bg-white rounded-2xl p-6 shadow-soft sticky top-24">
            <h2 class="text-lg font-bold text-charcoal mb-4">Récapitulatif</h2>
            
            <!-- Items -->
            <div class="space-y-3 mb-4">
              <div
                v-for="item in items"
                :key="item.product.id"
                class="flex gap-3"
              >
                <img
                  :src="item.product.image || '/images/placeholder.png'"
                  :alt="item.product.title"
                  class="w-16 h-16 rounded-lg object-cover bg-gray-100"
                />
                <div class="flex-1 min-w-0">
                  <h4 class="font-medium text-sm text-charcoal line-clamp-1">{{ item.product.title }}</h4>
                  <p class="text-gray-500 text-sm">Qté: {{ item.quantity }}</p>
                  <p class="text-gold font-semibold text-sm">{{ formatPrice(item.product.price * item.quantity) }}</p>
                </div>
              </div>
            </div>

            <hr class="my-4 border-gray-100" />

            <!-- Totaux -->
            <div class="space-y-2 text-sm">
              <div class="flex justify-between">
                <span class="text-gray-600">Sous-total</span>
                <span class="font-medium">{{ formatPrice(subtotal) }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-gray-600">Livraison</span>
                <span class="text-gold font-medium">À confirmer</span>
              </div>
            </div>

            <hr class="my-4 border-gray-100" />

            <div class="flex justify-between items-center mb-6">
              <span class="font-bold text-charcoal">Total</span>
              <span class="text-xl font-bold text-charcoal">{{ formatPrice(subtotal) }}</span>
            </div>

            <!-- Bouton Commander -->
            <button
              @click="submitOrder"
              :disabled="isSubmitting"
              class="w-full bg-charcoal text-white py-4 rounded-xl font-bold hover:bg-charcoal-800 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              <span v-if="isSubmitting" class="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              <span v-else>
                <svg class="w-5 h-5 inline mr-1" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51l-.57-.01c-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/>
                </svg>
                Commander via WhatsApp
              </span>
            </button>

            <p class="text-xs text-gray-500 text-center mt-3">
              Vous serez redirigé vers WhatsApp pour confirmer votre commande
            </p>
          </div>
        </div>
      </div>
    </div>

    <WhatsAppFloat />
  </div>
</template>

<script setup lang="ts">
import { CHAD_CITIES, PAYMENT_METHOD_LABELS } from '~/types'
import type { PaymentMethod } from '~/types'

useHead({
  title: 'Commander — Samiah Cosmetics',
})

const config = useRuntimeConfig()
const router = useRouter()
const { items, subtotal, isEmpty, formatPrice, clearCart } = useCart()
const { createOrder } = useOrders()

// Villes
const cities = CHAD_CITIES

// Modes de paiement
const paymentMethods = [
  { value: 'cash', label: 'Cash à la livraison', icon: '💵' },
  { value: 'airtel_money', label: 'Airtel Money', icon: '📱' },
  { value: 'moov_money', label: 'Moov Money', icon: '📱' },
  { value: 'western_union', label: 'Western Union', icon: '🏦' },
  { value: 'express_union', label: 'Express Union', icon: '🏦' },
  { value: 'moneygram', label: 'MoneyGram', icon: '🏦' },
]

// Formulaire
const form = reactive({
  name: '',
  phone: '',
  city: '',
  address: '',
  paymentMethod: 'cash' as PaymentMethod,
  notes: '',
})

const errors = reactive({
  name: '',
  phone: '',
  city: '',
  address: '',
  paymentMethod: '',
})

const isSubmitting = ref(false)

// Validation
const validate = () => {
  let isValid = true
  
  // Reset errors
  Object.keys(errors).forEach(key => {
    errors[key as keyof typeof errors] = ''
  })
  
  if (!form.name.trim()) {
    errors.name = 'Le nom est requis'
    isValid = false
  }
  
  if (!form.phone.trim()) {
    errors.phone = 'Le téléphone est requis'
    isValid = false
  } else if (!/^[0-9\s+()-]{8,}$/.test(form.phone)) {
    errors.phone = 'Numéro de téléphone invalide'
    isValid = false
  }
  
  if (!form.city) {
    errors.city = 'La ville est requise'
    isValid = false
  }
  
  if (!form.address.trim()) {
    errors.address = 'L\'adresse est requise'
    isValid = false
  }
  
  if (!form.paymentMethod) {
    errors.paymentMethod = 'Sélectionnez un mode de paiement'
    isValid = false
  }
  
  return isValid
}

// Soumettre la commande
const submitOrder = async () => {
  if (!validate()) return
  
  isSubmitting.value = true
  
  try {
    // Créer la commande dans Supabase
    const { order, error } = await createOrder({
      client_name: form.name,
      client_phone: form.phone,
      client_city: form.city,
      client_address: form.address,
      items: items.value.map(item => ({
        product_id: item.product.id,
        quantity: item.quantity,
      })),
      payment_method: form.paymentMethod,
      notes: form.notes || undefined,
    })
    
    if (error || !order) {
      alert('Erreur lors de la création de la commande. Veuillez réessayer.')
      return
    }
    
    // Générer le message WhatsApp
    const message = generateWhatsAppMessage(order)
    
    // Ouvrir WhatsApp
    const whatsappUrl = `https://wa.me/${config.public.whatsappNumber}?text=${message}`
    window.open(whatsappUrl, '_blank')
    
    // Vider le panier
    clearCart()
    
    // Rediriger vers la page de confirmation
    router.push(`/commande/${order.id}`)
    
  } catch (e) {
    console.error(e)
    alert('Une erreur est survenue. Veuillez réessayer.')
  } finally {
    isSubmitting.value = false
  }
}

// Générer le message WhatsApp
const generateWhatsAppMessage = (order: any) => {
  let msg = `🛒 *NOUVELLE COMMANDE #${order.order_number}*\n\n`
  msg += `👤 *Client:* ${order.client_name}\n`
  msg += `📱 *Tél:* ${order.client_phone}\n`
  msg += `📍 *Adresse:* ${order.client_address}, ${order.client_city}\n\n`
  msg += `📦 *Produits:*\n`
  
  order.items.forEach((item: any) => {
    msg += `• ${item.product_title} x${item.quantity} — ${formatPrice(item.subtotal)}\n`
  })
  
  msg += `\n💰 *Sous-total:* ${formatPrice(order.subtotal)}\n`
  msg += `🚚 *Livraison:* À confirmer selon le quartier\n\n`
  
  const paymentLabel = PAYMENT_METHOD_LABELS[order.payment_method as PaymentMethod]
  msg += `💳 *Paiement:* ${paymentLabel}\n`
  
  if (order.notes) {
    msg += `\n📝 *Notes:* ${order.notes}\n`
  }
  
  msg += `\n✨ Merci de confirmer ma commande !`
  
  return encodeURIComponent(msg)
}
</script>
