// pages/produits/index.vue
<template>
  <div class="min-h-screen bg-white">
    <!-- Header -->
    <div class="bg-gray-50 border-b border-gray-100">
      <div class="max-w-7xl mx-auto px-4 py-16 lg:py-24 text-center">
        <span class="inline-flex items-center gap-2 text-gold font-medium text-[10px] uppercase tracking-widest mb-4">
          <span class="w-6 h-px bg-gold"></span>
          Catalogue
          <span class="w-6 h-px bg-gold"></span>
        </span>
        <h1 class="text-3xl lg:text-5xl font-serif font-light text-charcoal">
          Nos Produits
        </h1>
        <p class="text-gray-500 font-light mt-4 max-w-xl mx-auto text-sm">
          Découvrez notre sélection de soins capillaires naturels pour sublimer vos cheveux
        </p>
      </div>
    </div>

    <div class="max-w-7xl mx-auto px-4 py-12">
      <!-- Filtres -->
      <div class="mb-12">
        <div class="flex flex-wrap items-center gap-4">
          <!-- Recherche -->
          <div class="flex-1 min-w-[200px]">
            <div class="relative">
              <svg class="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              <input
                v-model="filters.search"
                type="text"
                placeholder="Rechercher un produit..."
                class="w-full pl-12 pr-4 py-3 bg-gray-50 border border-transparent rounded-none focus:outline-none focus:bg-white focus:border-gray-200 transition-all text-sm text-charcoal placeholder:text-gray-400 font-light"
              />
            </div>
          </div>

          <!-- Catégorie -->
          <select
            v-model="filters.category"
            class="px-4 py-3 bg-gray-50 border border-transparent focus:outline-none focus:bg-white focus:border-gray-200 transition-all cursor-pointer text-sm text-charcoal font-light rounded-none min-w-[150px]"
          >
            <option v-for="cat in categories" :key="cat" :value="cat">
              {{ cat }}
            </option>
          </select>

          <!-- Ville -->
          <select
            v-model="filters.city"
            class="px-4 py-3 bg-gray-50 border border-transparent focus:outline-none focus:bg-white focus:border-gray-200 transition-all cursor-pointer text-sm text-charcoal font-light rounded-none min-w-[150px]"
          >
            <option value="Toutes">Toutes les villes</option>
            <option v-for="city in cities" :key="city" :value="city">
              {{ city }}
            </option>
          </select>

          <!-- Tri -->
          <select
            v-model="filters.sort"
            class="px-4 py-3 bg-gray-50 border border-transparent focus:outline-none focus:bg-white focus:border-gray-200 transition-all cursor-pointer text-sm text-charcoal font-light rounded-none min-w-[150px]"
          >
            <option value="newest">Plus récents</option>
            <option value="oldest">Plus anciens</option>
            <option value="price_asc">Prix croissant</option>
            <option value="price_desc">Prix décroissant</option>
            <option value="title_asc">Nom A-Z</option>
          </select>
        </div>

        <!-- Résultats count -->
        <div class="mt-4 flex items-center justify-between">
          <span class="text-xs uppercase tracking-widest text-gray-400 font-medium">
            <span class="text-charcoal">{{ filteredProducts.length }}</span> résultat{{ filteredProducts.length > 1 ? 's' : '' }}
          </span>
          <button 
            v-if="filters.search || filters.category !== 'Toutes' || filters.city !== 'Toutes'"
            @click="resetFilters"
            class="text-[10px] tracking-widest uppercase text-charcoal hover:text-gold transition-colors font-medium border-b border-transparent hover:border-gold pb-0.5"
          >
            Réinitialiser les filtres
          </button>
        </div>
      </div>

      <!-- Loading -->
      <div v-if="loading" class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 lg:gap-8">
        <SkeletonLoader v-for="i in 12" :key="i" type="product-card" />
      </div>

      <!-- Produits -->
      <div v-else-if="filteredProducts.length" class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 lg:gap-8">
        <ProductCard
          v-for="product in filteredProducts"
          :key="product.id"
          :product="product"
          show-add-to-cart
          @click="goToProduct(product)"
          @add-to-cart="addToCart"
        />
      </div>

      <!-- Aucun produit -->
      <div v-else class="text-center py-32 border border-gray-100">
        <p class="text-lg font-serif text-charcoal mb-4">Aucun produit trouvé</p>
        <p class="text-gray-500 font-light text-sm mb-8">Essayez de modifier vos filtres de recherche.</p>
        <button
          @click="resetFilters"
          class="inline-flex items-center gap-2 text-[10px] tracking-widest uppercase bg-charcoal text-white px-8 py-3 hover:bg-gold transition-colors"
        >
          Réinitialiser
        </button>
      </div>
    </div>


  </div>
</template>

<script setup lang="ts">
import type { Product, SortOption } from '~/types'
import { CHAD_CITIES } from '~/types'

useHead({
  title: 'Produits — Samiah Cosmetics',
  meta: [
    { name: 'description', content: 'Découvrez notre sélection de produits cosmétiques et soins capillaires au Tchad.' }
  ]
})

const { products, loading, fetchProducts, filterProducts, categories } = useProducts()
const { addItem } = useCart()

const cities = CHAD_CITIES

const filters = reactive({
  search: '',
  category: 'Toutes',
  city: 'Toutes',
  sort: 'newest' as SortOption
})

// Fetch products
await fetchProducts()

// Filtered products
const filteredProducts = computed(() => {
  return filterProducts(products.value, {
    search: filters.search,
    category: filters.category === 'Toutes' ? null : filters.category,
    city: filters.city === 'Toutes' ? null : filters.city,
    sort: filters.sort
  })
})

// Actions
const goToProduct = (product: Product) => {
  navigateTo(`/produits/${product.id}`)
}

const addToCart = (product: Product) => {
  addItem(product, 1)
}

const resetFilters = () => {
  filters.search = ''
  filters.category = 'Toutes'
  filters.city = 'Toutes'
  filters.sort = 'newest'
}
</script>

// src/app/produits/page.tsx
"use client";

import { useState, useEffect } from "react";
import ProductCard from "@/components/ProductCard";
import { supabase } from "@/lib/supabase";

export default function ProduitsPage() {
  const [selectedCategory, setSelectedCategory] = useState("tous");
  const [sortBy, setSortBy] = useState("default");
  const [products, setProducts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadProducts() {
      try {
        const { data, error } = await supabase
          .from("products")
          .select("*")
          .eq("active", true)
          .order("created_at", { ascending: false });
        
        if (error) throw error;
        setProducts(data || []);
      } catch (err) {
        console.error("Erreur de chargement des produits:", err);
      } finally {
        setLoading(false);
      }
    }
    loadProducts();
  }, []);

  const categories = [
    { id: "tous", label: "Toutes les catégories" },
    { id: "Soins Capillaires", label: "Soins Capillaires" },
    { id: "Soins Visage", label: "Soins Visage" },
    { id: "Soins Corps", label: "Soins Corps" }
  ];

  // Filtering
  const filteredProducts = products.filter(product => {
    if (selectedCategory === "tous") return true;
    return product.category === selectedCategory;
  });

  // Sorting
  const sortedProducts = [...filteredProducts].sort((a, b) => {
    if (sortBy === "price-asc") return a.price - b.price;
    if (sortBy === "price-desc") return b.price - a.price;
    if (sortBy === "alpha") return a.title.localeCompare(b.title);
    return 0; // Default
  });

  // Helper to determine if a product is new (within 7 days)
  const isNewProduct = (dateStr: string) => {
    if (!dateStr) return false;
    const created = Date.parse(dateStr);
    const sevenDays = 7 * 24 * 60 * 60 * 1000;
    return (Date.now() - created) <= sevenDays;
  };

  return (
    <div className="min-h-screen bg-cream pt-32 pb-24">
      <div className="max-w-7xl mx-auto px-6 sm:px-8 lg:px-12">
        
        {/* Header Catalogue */}
        <div className="flex flex-col lg:flex-row justify-between lg:items-end gap-8 mb-16 border-b border-sand/40 pb-10">
          <div className="space-y-4">
            <span className="text-[10px] font-semibold tracking-[0.25em] uppercase text-gold">La Boutique</span>
            <h1 className="text-4xl lg:text-5xl font-serif font-light text-charcoal">La Collection Samiah</h1>
            <p className="text-sm font-light text-charcoal/50">Explorez notre sélection méticuleuse d'essentiels botaniques.</p>
          </div>
          
          <div className="flex flex-col sm:flex-row gap-6 w-full lg:w-auto items-start sm:items-center">
            {/* Sorting dropdown */}
            <div className="flex items-center gap-3 w-full sm:w-auto">
              <span className="text-[9px] uppercase tracking-widest text-charcoal/40 font-medium">Trier par:</span>
              <select 
                value={sortBy} 
                onChange={(e) => setSortBy(e.target.value)}
                className="bg-transparent border-b border-sand text-charcoal text-[10px] uppercase tracking-[0.2em] py-2 outline-none cursor-pointer focus:border-gold transition-colors flex-1 sm:flex-none"
              >
                <option value="default">Par défaut</option>
                <option value="price-asc">Prix croissant</option>
                <option value="price-desc">Prix décroissant</option>
                <option value="alpha">Ordre alphabétique</option>
              </select>
            </div>
          </div>
        </div>

        {/* Categories Tabs */}
        <div className="flex flex-wrap gap-3 mb-16 border-b border-sand/10 pb-6">
          {categories.map(cat => (
            <button
              key={cat.id}
              onClick={() => setSelectedCategory(cat.id)}
              className={`px-6 py-2.5 text-[9px] uppercase tracking-[0.2em] font-semibold rounded-full border transition-all duration-300 ${
                selectedCategory === cat.id
                  ? "bg-charcoal text-white border-charcoal"
                  : "bg-transparent text-charcoal/60 border-sand hover:text-charcoal hover:border-charcoal/40"
              }`}
            >
              {cat.label}
            </button>
          ))}
        </div>

        {/* Count & Status */}
        <div className="mb-8 flex justify-between items-center text-[10px] uppercase tracking-widest text-charcoal/45">
          <span>{loading ? "Chargement..." : `${sortedProducts.length} produits trouvés`}</span>
        </div>

        {/* Loading State Skeletons */}
        {loading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
            {Array.from({ length: 4 }).map((_, idx) => (
              <div key={idx} className="animate-pulse flex flex-col space-y-4">
                <div className="aspect-[4/5] bg-sand/30 rounded-sm w-full" />
                <div className="h-4 bg-sand/30 rounded-sm w-2/3 mx-auto" />
                <div className="h-3 bg-sand/30 rounded-sm w-1/2 mx-auto" />
              </div>
            ))}
          </div>
        ) : sortedProducts.length === 0 ? (
          <div className="text-center py-24 border border-sand/40 rounded-sm">
            <p className="text-lg font-serif font-light text-charcoal mb-2">Aucun produit trouvé</p>
            <p className="text-xs text-charcoal/40 font-light">Essayez de sélectionner une autre catégorie.</p>
          </div>
        ) : (
          /* Grille Produits */
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
            {sortedProducts.map(product => (
              <div key={product.id} className="animate-fade-in">
                <ProductCard product={{
                  id: product.id,
                  title: product.title,
                  price: product.price,
                  image: product.image,
                  category: product.category,
                  isNew: isNewProduct(product.created_at)
                }} />
              </div>
            ))}
          </div>
        )}

      </div>
    </div>
  );
}
