// pages/admin/commandes.vue
<template>
  <div>
    <div class="flex items-center justify-between mb-6">
      <div>
        <h1 class="text-2xl font-bold text-charcoal">Commandes</h1>
        <p class="text-gray-500">Gérez toutes les commandes</p>
      </div>
    </div>

    <!-- Filters -->
    <div class="bg-white rounded-2xl shadow-soft p-4 mb-6">
      <div class="flex flex-wrap items-center gap-4">
        <!-- Search -->
        <div class="flex-1 min-w-[200px]">
          <div class="relative">
            <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            <input
              v-model="search"
              type="text"
              placeholder="Rechercher par nom, numéro..."
              class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-gold/50 focus:border-gold outline-none"
            />
          </div>
        </div>

        <!-- Status filter -->
        <select
          v-model="statusFilter"
          class="px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-gold/50 focus:border-gold outline-none"
        >
          <option value="">Tous les statuts</option>
          <option value="pending">En attente</option>
          <option value="confirmed">Confirmée</option>
          <option value="shipped">Expédiée</option>
          <option value="delivered">Livrée</option>
          <option value="cancelled">Annulée</option>
        </select>

        <!-- Refresh -->
        <button
          @click="fetchOrders"
          class="p-2.5 bg-gray-50 border border-gray-200 rounded-xl hover:bg-gray-100 transition-colors"
        >
          <svg class="w-5 h-5 text-gray-600" :class="{ 'animate-spin': loading }" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
          </svg>
        </button>
      </div>
    </div>

    <!-- Orders List -->
    <div class="bg-white rounded-2xl shadow-soft overflow-hidden">
      <!-- Loading -->
      <div v-if="loading" class="p-8">
        <div class="animate-pulse space-y-4">
          <div v-for="i in 5" :key="i" class="h-20 bg-gray-100 rounded-xl" />
        </div>
      </div>

      <!-- Empty -->
      <div v-else-if="filteredOrders.length === 0" class="p-12 text-center">
        <div class="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
          <svg class="w-10 h-10 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
          </svg>
        </div>
        <p class="text-gray-500">Aucune commande trouvée</p>
      </div>

      <!-- Orders -->
      <div v-else class="divide-y divide-gray-100">
        <div
          v-for="order in filteredOrders"
          :key="order.id"
          class="p-4 hover:bg-gray-50 transition-colors"
        >
          <div class="flex items-start justify-between gap-4">
            <!-- Order Info -->
            <div class="flex items-start gap-4 flex-1">
              <div class="w-12 h-12 bg-charcoal/10 rounded-xl flex items-center justify-center flex-shrink-0">
                <span class="font-bold text-charcoal">
                  {{ order.client_name.charAt(0).toUpperCase() }}
                </span>
              </div>
              <div class="flex-1 min-w-0">
                <div class="flex items-center gap-2 flex-wrap">
                  <p class="font-bold text-charcoal">{{ order.order_number }}</p>
                  <span
                    class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium"
                    :class="statusClass(order.status)"
                  >
                    {{ statusLabel(order.status) }}
                  </span>
                </div>
                <p class="text-gray-600">{{ order.client_name }} • {{ order.client_phone }}</p>
                <p class="text-sm text-gray-400">{{ order.client_address }}, {{ order.client_city }}</p>
                <p class="text-xs text-gray-400 mt-1">{{ formatDate(order.created_at) }}</p>
              </div>
            </div>

            <!-- Amount & Actions -->
            <div class="text-right flex-shrink-0">
              <p class="text-lg font-bold text-charcoal">{{ formatPrice(order.total) }}</p>
              <p class="text-sm text-gray-400">{{ order.items?.length || 0 }} article(s)</p>
              
              <div class="flex items-center gap-2 mt-2">
                <!-- WhatsApp -->
                <a
                  :href="getWhatsAppLink(order)"
                  target="_blank"
                  class="p-2 bg-[#25D366]/10 text-[#25D366] rounded-lg hover:bg-[#25D366]/20 transition-colors"
                  title="Contacter sur WhatsApp"
                >
                  <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51l-.57-.01c-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/>
                  </svg>
                </a>

                <!-- View Details -->
                <button
                  @click="openOrderDetails(order)"
                  class="p-2 bg-gray-100 text-gray-600 rounded-lg hover:bg-gray-200 transition-colors"
                  title="Voir les détails"
                >
                  <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                  </svg>
                </button>

                <!-- Status dropdown -->
                <select
                  :value="order.status"
                  @change="updateStatus(order.id, ($event.target as HTMLSelectElement).value)"
                  class="px-2 py-1 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-gold/50 focus:border-gold outline-none"
                >
                  <option value="pending">En attente</option>
                  <option value="confirmed">Confirmée</option>
                  <option value="shipped">Expédiée</option>
                  <option value="delivered">Livrée</option>
                  <option value="cancelled">Annulée</option>
                </select>
              </div>
            </div>
          </div>

          <!-- Order Items (collapsed) -->
          <div v-if="expandedOrder === order.id" class="mt-4 pt-4 border-t border-gray-100">
            <div class="grid sm:grid-cols-2 gap-4">
              <div>
                <h4 class="font-medium text-charcoal mb-2">Produits</h4>
                <div class="space-y-2">
                  <div
                    v-for="(item, idx) in order.items"
                    :key="idx"
                    class="flex justify-between text-sm"
                  >
                    <span class="text-gray-600">{{ item.product_title }} × {{ item.quantity }}</span>
                    <span class="font-medium">{{ formatPrice(item.subtotal) }}</span>
                  </div>
                </div>
              </div>
              <div>
                <h4 class="font-medium text-charcoal mb-2">Paiement</h4>
                <p class="text-sm text-gray-600">{{ paymentLabel(order.payment_method) }}</p>
                <p v-if="order.notes" class="text-sm text-gray-400 mt-2">
                  <span class="font-medium">Notes:</span> {{ order.notes }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Order Details Modal -->
    <Teleport to="body">
      <Transition
        enter-active-class="transition-opacity duration-200"
        enter-from-class="opacity-0"
        enter-to-class="opacity-100"
        leave-active-class="transition-opacity duration-150"
        leave-from-class="opacity-100"
        leave-to-class="opacity-0"
      >
        <div
          v-if="selectedOrder"
          class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
          @click.self="selectedOrder = null"
        >
          <div class="bg-white rounded-2xl shadow-xl max-w-lg w-full max-h-[90vh] overflow-y-auto">
            <!-- Header -->
            <div class="flex items-center justify-between p-6 border-b border-gray-100">
              <h2 class="text-lg font-bold text-charcoal">Commande {{ selectedOrder.order_number }}</h2>
              <button @click="selectedOrder = null" class="p-2 hover:bg-gray-100 rounded-lg">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            <!-- Content -->
            <div class="p-6 space-y-6">
              <!-- Status -->
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">Statut</label>
                <select
                  :value="selectedOrder.status"
                  @change="updateStatus(selectedOrder.id, ($event.target as HTMLSelectElement).value); selectedOrder.status = ($event.target as HTMLSelectElement).value"
                  class="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-gold/50 focus:border-gold outline-none"
                >
                  <option value="pending">🟡 En attente</option>
                  <option value="confirmed">🔵 Confirmée</option>
                  <option value="shipped">🟣 Expédiée</option>
                  <option value="delivered">🟢 Livrée</option>
                  <option value="cancelled">🔴 Annulée</option>
                </select>
              </div>

              <!-- Client -->
              <div class="bg-gray-50 rounded-xl p-4">
                <h3 class="font-medium text-charcoal mb-2">Client</h3>
                <p class="text-gray-600">{{ selectedOrder.client_name }}</p>
                <p class="text-gray-600">{{ selectedOrder.client_phone }}</p>
                <p class="text-gray-600">{{ selectedOrder.client_address }}, {{ selectedOrder.client_city }}</p>
              </div>

              <!-- Products -->
              <div>
                <h3 class="font-medium text-charcoal mb-2">Produits</h3>
                <div class="space-y-2">
                  <div
                    v-for="(item, idx) in selectedOrder.items"
                    :key="idx"
                    class="flex justify-between py-2 border-b border-gray-100 last:border-0"
                  >
                    <div>
                      <p class="font-medium text-charcoal">{{ item.product_title }}</p>
                      <p class="text-sm text-gray-500">{{ formatPrice(item.product_price) }} × {{ item.quantity }}</p>
                    </div>
                    <p class="font-bold text-charcoal">{{ formatPrice(item.subtotal) }}</p>
                  </div>
                </div>
              </div>

              <!-- Total -->
              <div class="bg-charcoal text-white rounded-xl p-4">
                <div class="flex justify-between mb-1">
                  <span class="text-white/70">Sous-total</span>
                  <span>{{ formatPrice(selectedOrder.subtotal) }}</span>
                </div>
                <div class="flex justify-between mb-2">
                  <span class="text-white/70">Livraison</span>
                  <span>{{ selectedOrder.shipping_fee > 0 ? formatPrice(selectedOrder.shipping_fee) : 'À confirmer' }}</span>
                </div>
                <div class="flex justify-between text-lg font-bold pt-2 border-t border-white/20">
                  <span>Total</span>
                  <span class="text-gold">{{ formatPrice(selectedOrder.total) }}</span>
                </div>
              </div>

              <!-- Actions -->
              <div class="flex gap-3">
                <a
                  :href="getWhatsAppLink(selectedOrder)"
                  target="_blank"
                  class="flex-1 bg-[#25D366] text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2"
                >
                  <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51l-.57-.01c-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/>
                  </svg>
                  Contacter
                </a>
                <button
                  @click="selectedOrder = null"
                  class="flex-1 bg-gray-100 text-charcoal py-3 rounded-xl font-bold"
                >
                  Fermer
                </button>
              </div>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ORDER_STATUS_LABELS, PAYMENT_METHOD_LABELS } from '~/types'
import type { Order, OrderStatus, PaymentMethod } from '~/types'

definePageMeta({
  layout: 'admin',
  middleware: 'auth',
})

useHead({
  title: 'Commandes — Admin Samiah',
})

const supabase = useSupabaseClient()
const route = useRoute()

const loading = ref(true)
const orders = ref<Order[]>([])
const search = ref('')
const statusFilter = ref(route.query.status as string || '')
const expandedOrder = ref<string | null>(null)
const selectedOrder = ref<Order | null>(null)

// Filtered orders
const filteredOrders = computed(() => {
  let result = orders.value

  if (search.value) {
    const q = search.value.toLowerCase()
    result = result.filter(o =>
      o.order_number.toLowerCase().includes(q) ||
      o.client_name.toLowerCase().includes(q) ||
      o.client_phone.includes(q)
    )
  }

  if (statusFilter.value) {
    result = result.filter(o => o.status === statusFilter.value)
  }

  return result
})

// Fetch orders
const fetchOrders = async () => {
  loading.value = true
  try {
    const { data, error } = await supabase
      .from('orders')
      .select('*')
      .order('created_at', { ascending: false })

    if (error) throw error
    orders.value = data || []
  } catch (error) {
    console.error('Error fetching orders:', error)
  } finally {
    loading.value = false
  }
}

// Update status
const updateStatus = async (orderId: string, newStatus: string) => {
  try {
    const { error } = await supabase
      .from('orders')
      .update({ status: newStatus, updated_at: new Date().toISOString() })
      .eq('id', orderId)

    if (error) throw error

    // Update local state
    const order = orders.value.find(o => o.id === orderId)
    if (order) order.status = newStatus as OrderStatus
  } catch (error) {
    console.error('Error updating status:', error)
    alert('Erreur lors de la mise à jour du statut')
  }
}

// Helpers
const formatPrice = (price: number) => new Intl.NumberFormat('fr-FR').format(price) + ' F'

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString('fr-FR', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

const statusLabel = (status: string) => ORDER_STATUS_LABELS[status as OrderStatus] || status

const statusClass = (status: string) => {
  const classes: Record<string, string> = {
    pending: 'bg-yellow-100 text-yellow-800',
    confirmed: 'bg-blue-100 text-blue-800',
    shipped: 'bg-purple-100 text-purple-800',
    delivered: 'bg-green-100 text-green-800',
    cancelled: 'bg-red-100 text-red-800',
  }
  return classes[status] || 'bg-gray-100 text-gray-800'
}

const paymentLabel = (method: string) => PAYMENT_METHOD_LABELS[method as PaymentMethod] || method

const getWhatsAppLink = (order: Order) => {
  const msg = `Bonjour ${order.client_name}, concernant votre commande #${order.order_number}...`
  return `https://wa.me/${order.client_phone.replace(/\s/g, '')}?text=${encodeURIComponent(msg)}`
}

const openOrderDetails = (order: Order) => {
  selectedOrder.value = order
}

// Real-time updates
onMounted(async () => {
  await fetchOrders()

  const channel = supabase
    .channel('orders-changes')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'orders' }, () => {
      fetchOrders()
    })
    .subscribe()

  onUnmounted(() => {
    supabase.removeChannel(channel)
  })
})
</script>

// src/app/admin/commandes/page.tsx
"use client";

import { useEffect, useState } from "react";
import { 
  Search, 
  Filter, 
  Phone, 
  MapPin, 
  Clock, 
  CheckCircle2, 
  Truck, 
  XCircle, 
  ChevronRight,
  Package,
  MessageCircle,
  RefreshCw
} from "lucide-react";
import { fetchAdminData, AdminOrder } from "@/lib/admin-data";

export default function AdminOrdersPage() {
  const [orders, setOrders] = useState<AdminOrder[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [selectedOrder, setSelectedOrder] = useState<AdminOrder | null>(null);

  const loadOrders = async () => {
    setLoading(true);
    try {
      const data = await fetchAdminData();
      setOrders(data.orders);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadOrders();
  }, []);

  const handleStatusChange = (orderId: string, newStatus: AdminOrder["status"]) => {
    setOrders((prev) =>
      prev.map((o) => (o.id === orderId ? { ...o, status: newStatus } : o))
    );
    if (selectedOrder && selectedOrder.id === orderId) {
      setSelectedOrder((prev) => (prev ? { ...prev, status: newStatus } : null));
    }
  };

  const filteredOrders = orders.filter((order) => {
    const matchesSearch =
      order.order_number.toLowerCase().includes(searchTerm.toLowerCase()) ||
      order.client_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      order.client_phone.toLowerCase().includes(searchTerm.toLowerCase()) ||
      order.client_city.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesStatus =
      statusFilter === "all" || order.status === statusFilter;

    return matchesSearch && matchesStatus;
  });

  const getStatusBadge = (status: AdminOrder["status"]) => {
    switch (status) {
      case "delivered":
        return (
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium bg-emerald-50 text-emerald-700 border border-emerald-200">
            <CheckCircle2 className="w-3 h-3" />
            Livrée
          </span>
        );
      case "shipped":
        return (
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium bg-blue-50 text-blue-700 border border-blue-200">
            <Truck className="w-3 h-3" />
            Expédiée
          </span>
        );
      case "processing":
        return (
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium bg-amber-50 text-amber-700 border border-amber-200">
            <Clock className="w-3 h-3" />
            En préparation
          </span>
        );
      case "cancelled":
        return (
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium bg-red-50 text-red-700 border border-red-200">
            <XCircle className="w-3 h-3" />
            Annulée
          </span>
        );
      default:
        return (
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-700 border border-gray-200">
            <Clock className="w-3 h-3" />
            En attente
          </span>
        );
    }
  };

  return (
    <div className="space-y-6">
      {/* Title */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-serif text-charcoal tracking-tight">Commandes</h1>
          <p className="text-sm text-gray-500 mt-1">Gérez et suivez le traitement des commandes clientes</p>
        </div>
        <button
          onClick={loadOrders}
          disabled={loading}
          className="inline-flex items-center gap-2 px-3 py-2 text-xs font-medium rounded-lg border border-gray-200 bg-white text-gray-700 hover:bg-gray-50 transition-colors shadow-2xs self-start"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
          Actualiser
        </button>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-white p-4 border border-gray-200/80 rounded-xl shadow-2xs flex flex-col md:flex-row gap-3 items-stretch md:items-center justify-between">
        <div className="relative flex-1">
          <Search className="w-4 h-4 text-gray-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Rechercher par N° commande, client, téléphone, ville..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2 text-sm bg-gray-50 border border-gray-200 rounded-lg focus:outline-none focus:border-gold focus:bg-white transition-colors"
          />
        </div>

        <div className="flex items-center gap-2 overflow-x-auto pb-1 md:pb-0">
          <Filter className="w-4 h-4 text-gray-400 flex-shrink-0" />
          {[
            { id: "all", label: "Toutes" },
            { id: "pending", label: "En attente" },
            { id: "processing", label: "En préparation" },
            { id: "shipped", label: "Expédiée" },
            { id: "delivered", label: "Livrée" },
            { id: "cancelled", label: "Annulée" },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setStatusFilter(tab.id)}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg whitespace-nowrap transition-colors ${
                statusFilter === tab.id
                  ? "bg-charcoal text-white"
                  : "bg-gray-100 text-gray-600 hover:bg-gray-200"
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* Orders List / Table */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className={selectedOrder ? "lg:col-span-7" : "lg:col-span-12"}>
          <div className="bg-white border border-gray-200/80 rounded-xl shadow-2xs overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm text-gray-600">
                <thead className="bg-gray-50/80 border-b border-gray-100 text-[11px] uppercase tracking-wider font-semibold text-gray-500">
                  <tr>
                    <th className="px-5 py-3.5">N° Commande</th>
                    <th className="px-5 py-3.5">Client</th>
                    <th className="px-5 py-3.5">Montant</th>
                    <th className="px-5 py-3.5">Paiement</th>
                    <th className="px-5 py-3.5">Statut</th>
                    <th className="px-5 py-3.5 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100 font-light">
                  {filteredOrders.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="px-6 py-12 text-center text-gray-400">
                        Aucune commande ne correspond à vos critères.
                      </td>
                    </tr>
                  ) : (
                    filteredOrders.map((order) => {
                      const isSelected = selectedOrder?.id === order.id;
                      return (
                        <tr
                          key={order.id}
                          onClick={() => setSelectedOrder(order)}
                          className={`cursor-pointer transition-colors ${
                            isSelected ? "bg-amber-50/50" : "hover:bg-gray-50/50"
                          }`}
                        >
                          <td className="px-5 py-4 font-mono font-medium text-charcoal text-xs">
                            {order.order_number}
                            <span className="block text-[10px] text-gray-400 font-sans mt-0.5">
                              {new Date(order.created_at).toLocaleDateString("fr-FR", {
                                day: "2-digit",
                                month: "short",
                                hour: "2-digit",
                                minute: "2-digit",
                              })}
                            </span>
                          </td>
                          <td className="px-5 py-4">
                            <p className="font-medium text-charcoal text-xs sm:text-sm">{order.client_name}</p>
                            <p className="text-xs text-gray-400">{order.client_city}</p>
                          </td>
                          <td className="px-5 py-4 font-medium text-charcoal text-xs sm:text-sm whitespace-nowrap">
                            {order.total.toLocaleString("fr-FR")} FCFA
                          </td>
                          <td className="px-5 py-4">
                            <span className={`inline-block px-2 py-0.5 rounded text-[10px] font-medium uppercase tracking-wider ${
                              order.payment_method === "kadryza"
                                ? "bg-purple-50 text-purple-700 border border-purple-200"
                                : "bg-emerald-50 text-emerald-700 border border-emerald-200"
                            }`}>
                              {order.payment_method === "kadryza" ? "Kadryza" : "Cash"}
                            </span>
                          </td>
                          <td className="px-5 py-4">
                            {getStatusBadge(order.status)}
                          </td>
                          <td className="px-5 py-4 text-right">
                            <button className="text-gray-400 hover:text-charcoal p-1">
                              <ChevronRight className="w-4 h-4" />
                            </button>
                          </td>
                        </tr>
                      );
                    })
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* Order Details Drawer / Card */}
        {selectedOrder && (
          <div className="lg:col-span-5 bg-white border border-gray-200/80 rounded-xl shadow-2xs p-5 sm:p-6 space-y-6 self-start sticky top-20">
            <div className="flex items-center justify-between border-b border-gray-100 pb-4">
              <div>
                <span className="text-[10px] uppercase font-bold tracking-widest text-gold">Détails commande</span>
                <h3 className="text-lg font-mono font-bold text-charcoal">{selectedOrder.order_number}</h3>
              </div>
              <button
                onClick={() => setSelectedOrder(null)}
                className="text-gray-400 hover:text-charcoal text-xs font-semibold px-2 py-1 bg-gray-100 rounded"
              >
                Fermer
              </button>
            </div>

            {/* Client Info */}
            <div className="space-y-3 bg-gray-50/70 p-4 rounded-lg border border-gray-100 text-xs">
              <p className="font-semibold text-charcoal text-sm">{selectedOrder.client_name}</p>
              <div className="flex items-center gap-2 text-gray-600">
                <Phone className="w-3.5 h-3.5 text-gray-400" />
                <span>{selectedOrder.client_phone}</span>
                <a
                  href={`https://wa.me/${selectedOrder.client_phone.replace(/[^0-9]/g, "")}`}
                  target="_blank"
                  rel="noreferrer"
                  className="ml-auto inline-flex items-center gap-1 text-[11px] text-emerald-600 hover:text-emerald-700 font-medium"
                >
                  <MessageCircle className="w-3.5 h-3.5" />
                  WhatsApp
                </a>
              </div>
              <div className="flex items-center gap-2 text-gray-600">
                <MapPin className="w-3.5 h-3.5 text-gray-400" />
                <span>{selectedOrder.client_city} — {selectedOrder.client_address}</span>
              </div>
            </div>

            {/* Items */}
            <div className="space-y-3">
              <p className="text-xs font-semibold uppercase tracking-wider text-gray-400">Articles commandés</p>
              <div className="divide-y divide-gray-100 border-t border-b border-gray-100 py-1">
                {selectedOrder.items.map((item, idx) => (
                  <div key={idx} className="py-2.5 flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      <Package className="w-3.5 h-3.5 text-gold" />
                      <div>
                        <p className="font-medium text-charcoal">{item.product_title || item.productId}</p>
                        <p className="text-gray-400">Qté : {item.quantity}</p>
                      </div>
                    </div>
                    <span className="font-medium text-charcoal">
                      {((item.product_price || item.price || 0) * item.quantity).toLocaleString("fr-FR")} FCFA
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Totals */}
            <div className="space-y-1.5 text-xs text-gray-600">
              <div className="flex justify-between">
                <span>Sous-total</span>
                <span>{selectedOrder.subtotal.toLocaleString("fr-FR")} FCFA</span>
              </div>
              <div className="flex justify-between">
                <span>Frais de livraison</span>
                <span>{selectedOrder.shipping_fee.toLocaleString("fr-FR")} FCFA</span>
              </div>
              <div className="flex justify-between font-bold text-charcoal text-sm pt-2 border-t border-gray-100">
                <span>Total</span>
                <span className="text-gold">{selectedOrder.total.toLocaleString("fr-FR")} FCFA</span>
              </div>
            </div>

            {/* Status change actions */}
            <div className="pt-2 space-y-2 border-t border-gray-100">
              <label className="text-xs font-semibold uppercase tracking-wider text-gray-400 block">
                Modifier le statut de la commande
              </label>
              <select
                value={selectedOrder.status}
                onChange={(e) =>
                  handleStatusChange(
                    selectedOrder.id,
                    e.target.value as AdminOrder["status"]
                  )
                }
                className="w-full text-xs font-medium p-2.5 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none focus:border-gold"
              >
                <option value="pending">En attente (Nouvelle commande)</option>
                <option value="processing">En préparation</option>
                <option value="shipped">Expédiée (En cours de livraison)</option>
                <option value="delivered">Livrée avec succès</option>
                <option value="cancelled">Annulée</option>
              </select>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
